### ISSUE TITLE
About the save and dependency

### ISSUE THREAD

**Issue by simongcc** [TroyBug/jscrop#1]
Hello! I have just tried your crop. Thanks for sharing.
When I use `npm install`, there are a few dependencies are missing:
- multer
- fileupload
- gm

and the `app.js` is not working because of multer setting
after setting it to
`app.use(multer({dest:'./public/images/'}).single('uploadBtn'));`

Then the page work, but the upload button is not functioning.
There is a `/save` seems missing. (believed to be save.ejs)
Would you mind sharing what will you doing in it? 
Many thanks again.

**Comment by TroyBug** [comment]
Hi,@simongcc ,thanks for using it.I just update some files to fix these bugs.
I am sorry about that the file package.json was incomplete before.The correct dependencies are these:
`"dependencies": {
    "body-parser": "~1.8.1",
    "cookie-parser": "~1.3.3",
    "debug": "~2.0.0",
    "ejs": "~0.8.5",
    "express": "~4.9.0",
    "fileupload": "^1.0.0",
    "gm": "^1.23.0",
    "morgan": "~1.3.0",
    "multer": "^1.2.0",
    "imagemagick": "~0.1.3",
    "serve-favicon": "~2.1.3"
  }`

and before you started,you should install graphicsMagic and ImageMagick,which are stand-alone programs,not a npm module.They can download from these links:
[http://www.graphicsmagick.org/](http://www.graphicsmagick.org/)
[http://www.imagemagick.org/](http://www.imagemagick.org/)

In Mac OS X, you can simply use Homebrew and do:
`brew install imagemagick
brew install graphicsmagick`

If you work on windows,it maybe needs you to restart your computer for environment variables.

save.ejs was not necessary cause route use it only to deal with the POST method and redirection.

Hope this helps  :)
